from django.urls import path, include
from .views import BookList
from rest_framework.routers import DefaultRouter
from .views import BookList, BookViewSet

urlpatterns = [
    path('books/', BookList.as_view(), name='book-list'),
]

# Setup router
router = DefaultRouter()
router.register(r'books_all', BookViewSet, basename='book_all')

urlpatterns = [
    # Still keep the simple ListAPIView route
    path('books/', BookList.as_view(), name='book-list'),

    # Add all routes generated by the router
    path('', include(router.urls)),
]
